name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # run once for each OS / Python combo
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add conda to PATH
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies & build
        run: |
          conda create -n test python=${{ matrix.python-version }} --yes
          source activate test
          conda config --add channels conda-forge
          conda install --yes numpy scipy nose requests pdbfixer mdtraj openmm
          conda install -c bioconda --yes clustalw
          pip install mmtf-python scikit-learn
          pip install .
          python setup.py build_ext --inplace --force

      - name: Test with pytest
        run: |
          source activate test
          conda install --yes pytest
          pytest
