name: Simple Checkout Test

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: list directory
        run: ls -al
